classdef myrupDelay < audioPlugin
   properties
      fs = 48000;
      bypass = false;
      tempo = 120;
      mix = 1;
      mix_gui = 100;
      fLpf1 = 2000;
      aLpf1 = 0;
      stLpf1 = zeros(1, 2);
      level4 = -6;
      level8dot = -6;
      level8 = -6;
      level16dot = -6;
      level16 = -6;
      level = zeros(5, 1);
      pan4 = 0;
      pan8dot = -50;
      pan8 = 50;
      pan16dot = 100;
      pan16 = -100;
      pan = zeros(5, 1);
      fb = 0;
      del = zeros(5, 1);
      dLine = zeros(76800 * 2, 2);
      storeLoc = 1;
   end
   properties (Constant)
      PluginInterface = audioPluginInterface(...
         audioPluginParameter('level4', ...
         'DisplayName', '1/4', ...
         'Mapping', {'lin', -100, 0}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [2, 1]), ...
         audioPluginParameter('level8dot', ...
         'DisplayName', '1/8.', ...
         'Mapping', {'lin', -100, 0}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [2, 2]), ...
         audioPluginParameter('level8', ...
         'DisplayName', '1/8', ...
         'Mapping', {'lin', -100, 0}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [2, 3]), ...
         audioPluginParameter('level16dot', ...
         'DisplayName', ' 1/16.', ...
         'Mapping', {'lin', -100, 0}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [2, 4]), ...
         audioPluginParameter('level16', ...
         'DisplayName', '1/16', ...
         'Mapping', {'lin', -100, 0}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [2, 5]), ...
         audioPluginParameter('pan4', ...
         'DisplayName', 'Pan', ...
         'Mapping', {'lin', -100, 100}, ...
         'Style', 'rotary', ...
         'Layout', [4, 1]), ...
         audioPluginParameter('pan8dot', ...
         'DisplayName', 'Pan', ...
         'Mapping', {'lin', -100, 100}, ...
         'Style', 'rotary', ...
         'Layout', [4, 2]), ...
         audioPluginParameter('pan8', ...
         'DisplayName', 'Pan', ...
         'Mapping', {'lin', -100, 100}, ...
         'Style', 'rotary', ...
         'Layout', [4, 3]), ...
         audioPluginParameter('pan16dot', ...
         'DisplayName', 'Pan', ...
         'Mapping', {'lin', -100, 100}, ...
         'Style', 'rotary', ...
         'Layout', [4, 4]), ...
         audioPluginParameter('pan16', ...
         'DisplayName', 'Pan', ...
         'Mapping', {'lin', -100, 100}, ...
         'Style', 'rotary', ...
         'Layout', [4, 5]), ...
         audioPluginParameter('tempo', ...
         'DisplayName', 'Tempo', ...
         'Mapping', {'lin', 60, 300}, ...
         'Label', 'bpm', ...
         'Style', 'rotary', ...
         'Layout', [6, 1]), ...
         audioPluginParameter('fLpf1', ...
         'DisplayName', 'Filter', ...
         'Mapping', {'log', 20, 20000}, ...
         'Label', 'Hz', ...
         'Style', 'rotary', ...
         'Layout', [6, 2]), ...
         audioPluginParameter('fb', ...
         'DisplayName', 'Feedback', ...
         'Mapping', {'lin', 0, 100}, ...
         'Label', '%', ...
         'Style', 'rotary', ...
         'Layout', [6, 3]), ...
         audioPluginParameter('mix_gui', ...
         'DisplayName', 'Mix', ...
         'Mapping', {'lin', 0, 100}, ...
         'Label', '%', ...
         'Style', 'rotary', ...
         'Layout', [6, 4]), ...
         audioPluginParameter('bypass', ...
         'Mapping', {'enum', 'In', 'Out'}, ...
         'Style', 'vtoggle', ...
         'Layout', [6, 5], ...
         'DisplayName', 'Master Bypass'), ...
         audioPluginGridLayout(...
         'RowHeight', [30, 100, 15, 100, 15, 100, 15], ...
         'ColumnWidth', [100, 100, 100, 100, 100], ...
         'RowSpacing', 30), ...
         'PluginName', 'myrupDelay', ...
         'VendorName', 'NT', ...
         'InputChannels', 2, ...
         'OutputChannels', 2, ...
         'BackgroundImage', 'logo.png' ...
         );
   end
   methods
      function set.tempo(p, val)
         p.tempo = val;
         update(p);
      end
      function set.mix_gui(p, val)
         p.mix_gui = val;
         update(p);
      end
      function set.level4(p, val)
         p.level4 = val;
         update(p);
      end
      function set.level8(p, val)
         p.level8 = val;
         update(p);
      end
      function set.level16(p, val)
         p.level16 = val;
         update(p);
      end
      function set.level16dot(p, val)
         p.level16dot = val;
         update(p);
      end
      function set.level8dot(p, val)
         p.level8dot = val;
         update(p);
      end
      function set.pan4(p, val)
         p.pan4 = val;
         update(p);
      end
      function set.pan8(p, val)
         p.pan8 = val;
         update(p);
      end
      function set.pan16(p, val)
         p.pan16 = val;
         update(p);
      end
      function set.pan16dot(p, val)
         p.pan16dot = val;
         update(p);
      end
      function set.pan8dot(p, val)
         p.pan8dot = val;
         update(p);
      end
      function set.fb(p, val)
         p.fb = val;
         update(p);
      end
      function set.fLpf1(p, val)
         p.fLpf1 = val;
         update(p);
      end
      function y = process(p, x)
         x(~isreal(x)) = 0;
         n = length(x);
         y = zeros(n, 2);
         if p.bypass == true
            y = x;
         else
            stLpf1_loc = p.stLpf1;
            for i = 1:n
               accum = [0 0];
               for j = 1:5
                  loc = p.storeLoc - p.del(j);
                  loc(loc < 1) = loc + 76800 * 2;
                  accum(1) = accum(1) + p.dLine(loc, 1) * p.level(j) * sqrt((1 - p.pan(j)));
                  accum(2) = accum(2) + p.dLine(loc, 2) * p.level(j) * sqrt(p.pan(j));
               end
               accumLpf = p.aLpf1 .* accum + (1 - p.aLpf1) * stLpf1_loc;
               stLpf1_loc = accumLpf;
               p.dLine(p.storeLoc, :) = x(i, :) + accumLpf * p.fb / 100;
               p.storeLoc = p.storeLoc + 1;
               p.storeLoc(p.storeLoc > 76800 * 2) = 1;
               y(i, :) = accumLpf * p.mix + x(i, :) * (1 - p.mix);
            end
            p.stLpf1 = stLpf1_loc;
         end
      end
      function update(p)
         p.mix = p.mix_gui / 100;
         p.del(1) = round(60 * p.fs / p.tempo);
         p.del(2) = round(60 * p.fs / p.tempo / 2);
         p.del(3) = round(60 * p.fs / p.tempo / 4);
         p.del(4) = round(60 * p.fs / p.tempo / 4 * 1.5);
         p.del(5) = round(60 * p.fs / p.tempo / 2 * 1.5);
         p.level(1) = 10^(p.level4 / 20);
         p.level(5) = 10^(p.level8dot / 20);
         p.level(2) = 10^(p.level8 / 20);
         p.level(4) = 10^(p.level16dot / 20);
         p.level(3) = 10^(p.level16 / 20);
         p.pan(1) = p.pan4 / 200 + 0.5;
         p.pan(5) = p.pan8dot / 200 + 0.5;
         p.pan(2) = p.pan8 / 200 + 0.5;
         p.pan(4) = p.pan16dot / 200 + 0.5;
         p.pan(3) = p.pan16 / 200 + 0.5;
         p.aLpf1 = 1 - exp(-2 .* pi .* p.fLpf1 ./ p.fs);
      end
      function reset(p)
         p.fs = getSampleRate(p);
         update(p);
      end
   end
end
