#include "lib/Biquad.h"
#include "lib/ComponentTest.h"
#include <memory>

int main() {
  auto set = NtFx::ComponentTestSet(std::string(testFileBaseName(__FILE__)));
  auto butterLpfSecond_   = std::make_unique<NtFx::Biquad::ButterLpfSecond>();
  auto butterLpfThird_    = std::make_unique<NtFx::Biquad::ButterLpfThird>();
  auto butterLpfFourth_   = std::make_unique<NtFx::Biquad::ButterLpfFourth>();
  auto butterLpfFifth_    = std::make_unique<NtFx::Biquad::ButterLpfFifth>();
  auto butterLpfSixth_    = std::make_unique<NtFx::Biquad::ButterLpfSixth>();
  auto butterLpfSeventh_  = std::make_unique<NtFx::Biquad::ButterLpfSeventh>();
  auto butterLpfEighth_   = std::make_unique<NtFx::Biquad::ButterLpfEighth>();
  auto butterHpfSecond_   = std::make_unique<NtFx::Biquad::ButterHpfSecond>();
  auto butterHpfThird_    = std::make_unique<NtFx::Biquad::ButterHpfThird>();
  auto butterHpfFourth_   = std::make_unique<NtFx::Biquad::ButterHpfFourth>();
  auto butterHpfFifth_    = std::make_unique<NtFx::Biquad::ButterHpfFifth>();
  auto butterHpfSixth_    = std::make_unique<NtFx::Biquad::ButterHpfSixth>();
  auto butterHpfSeventh_  = std::make_unique<NtFx::Biquad::ButterHpfSeventh>();
  auto butterHpfEighth_   = std::make_unique<NtFx::Biquad::ButterHpfEighth>();
  auto linkwitzLpfSecond_ = std::make_unique<NtFx::Biquad::LinkwitzLpfSecond>();
  auto linkwitzLpfFourth_ = std::make_unique<NtFx::Biquad::LinkwitzLpfFourth>();
  auto linkwitzLpfSixth_  = std::make_unique<NtFx::Biquad::LinkwitzLpfSixth>();
  auto linkwitzLpfEighth_ = std::make_unique<NtFx::Biquad::LinkwitzLpfEighth>();
  auto linkwitzHpfSecond_ = std::make_unique<NtFx::Biquad::LinkwitzHpfSecond>();
  auto linkwitzHpfFourth_ = std::make_unique<NtFx::Biquad::LinkwitzHpfFourth>();
  auto linkwitzHpfSixth_  = std::make_unique<NtFx::Biquad::LinkwitzHpfSixth>();
  auto linkwitzHpfEighth_ = std::make_unique<NtFx::Biquad::LinkwitzHpfEighth>();
  auto& butterLpfSecond   = *butterLpfSecond_;
  auto& butterLpfThird    = *butterLpfThird_;
  auto& butterLpfFourth   = *butterLpfFourth_;
  auto& butterLpfFifth    = *butterLpfFifth_;
  auto& butterLpfSixth    = *butterLpfSixth_;
  auto& butterLpfSeventh  = *butterLpfSeventh_;
  auto& butterLpfEighth   = *butterLpfEighth_;
  auto& butterHpfSecond   = *butterHpfSecond_;
  auto& butterHpfThird    = *butterHpfThird_;
  auto& butterHpfFourth   = *butterHpfFourth_;
  auto& butterHpfFifth    = *butterHpfFifth_;
  auto& butterHpfSixth    = *butterHpfSixth_;
  auto& butterHpfSeventh  = *butterHpfSeventh_;
  auto& butterHpfEighth   = *butterHpfEighth_;
  auto& linkwitzLpfSecond = *linkwitzLpfSecond_;
  auto& linkwitzLpfFourth = *linkwitzLpfFourth_;
  auto& linkwitzLpfSixth  = *linkwitzLpfSixth_;
  auto& linkwitzLpfEighth = *linkwitzLpfEighth_;
  auto& linkwitzHpfSecond = *linkwitzHpfSecond_;
  auto& linkwitzHpfFourth = *linkwitzHpfFourth_;
  auto& linkwitzHpfSixth  = *linkwitzHpfSixth_;
  auto& linkwitzHpfEighth = *linkwitzHpfEighth_;
  butterLpfSecond.fc_hz   = 200;
  butterLpfThird.fc_hz    = 200;
  butterLpfFourth.fc_hz   = 200;
  butterLpfFifth.fc_hz    = 200;
  butterLpfSixth.fc_hz    = 200;
  butterLpfSeventh.fc_hz  = 200;
  butterLpfEighth.fc_hz   = 200;
  butterHpfSecond.fc_hz   = 200;
  butterHpfThird.fc_hz    = 200;
  butterHpfFourth.fc_hz   = 200;
  butterHpfFifth.fc_hz    = 200;
  butterHpfSixth.fc_hz    = 200;
  butterHpfSeventh.fc_hz  = 200;
  butterHpfEighth.fc_hz   = 200;
  linkwitzLpfSecond.fc_hz = 2000;
  linkwitzLpfFourth.fc_hz = 2000;
  linkwitzLpfSixth.fc_hz  = 2000;
  linkwitzLpfEighth.fc_hz = 2000;
  linkwitzHpfSecond.fc_hz = 2000;
  linkwitzHpfFourth.fc_hz = 2000;
  linkwitzHpfSixth.fc_hz  = 2000;
  linkwitzHpfEighth.fc_hz = 2000;
  NTFX_ADD_TEST(set, butterLpfSecond, "impulse");
  NTFX_ADD_TEST(set, butterLpfThird, "impulse");
  NTFX_ADD_TEST(set, butterLpfFourth, "impulse");
  NTFX_ADD_TEST(set, butterLpfFifth, "impulse");
  NTFX_ADD_TEST(set, butterLpfSixth, "impulse");
  NTFX_ADD_TEST(set, butterLpfSeventh, "impulse");
  NTFX_ADD_TEST(set, butterLpfEighth, "impulse");
  NTFX_ADD_TEST(set, butterHpfSecond, "impulse");
  NTFX_ADD_TEST(set, butterHpfThird, "impulse");
  NTFX_ADD_TEST(set, butterHpfFourth, "impulse");
  NTFX_ADD_TEST(set, butterHpfFifth, "impulse");
  NTFX_ADD_TEST(set, butterHpfSixth, "impulse");
  NTFX_ADD_TEST(set, butterHpfSeventh, "impulse");
  NTFX_ADD_TEST(set, butterHpfEighth, "impulse");
  NTFX_ADD_TEST(set, linkwitzLpfSecond, "impulse");
  NTFX_ADD_TEST(set, linkwitzLpfFourth, "impulse");
  NTFX_ADD_TEST(set, linkwitzLpfSixth, "impulse");
  NTFX_ADD_TEST(set, linkwitzLpfEighth, "impulse");
  NTFX_ADD_TEST(set, linkwitzHpfSecond, "impulse");
  NTFX_ADD_TEST(set, linkwitzHpfFourth, "impulse");
  NTFX_ADD_TEST(set, linkwitzHpfSixth, "impulse");
  NTFX_ADD_TEST(set, linkwitzHpfEighth, "impulse");
  return set.runAllTests();
}