#! ./.venv/bin/python

"""
@file build.py
@author Niels Thøgersen (niels.thoegersen@gmail.com)
@brief Builds JUCE plugins from NTplugin sources.
@version 0.1

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.
This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
details.
You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

import os
import sys
import re
import subprocess
import shutil
import argparse
from multiprocessing import cpu_count
from . import package
from .package import RED, GREEN, BLUE, BLACK

REPO_BASE_DIR = os.path.realpath(os.path.dirname(__file__) + "/..")
BUILD_DIR = os.path.realpath(f"{REPO_BASE_DIR}/build")
JUCE_WRAPPER_DIR = os.path.realpath(f"{REPO_BASE_DIR}/JuceWrapper")
ID_FILE = os.path.realpath(f"{JUCE_WRAPPER_DIR}/pluginIds.txt")
ARTIFACTS_DIR = os.path.realpath(f"{REPO_BASE_DIR}/artifacts")
PLUGIN_H_FILE = f"{JUCE_WRAPPER_DIR}/Plugins.h"

ID = 0
VST3_CAT = 1
AAX_CAT = 2

"""
Maps from AAX format categories to VST3 format. AU doesn't make sense since 
the only applicable fromat there in 'Effect'.
Keys are AAX format, values are VST3 format.
"""
CATEGORY_MAP = {
    "Effect": "Fx",
    "EQ": "EQ",
    "Dynamics": "Dynamics",
    "Reverb": "Reverb",
    "Delay": "Delay",
    "PitchShift": "Pitch Shift",
    "Modulation": "Modulation",
    "Harmonic": "Distortion",
    "NoiseReduction": "Restoration",
    "SoundField": "Spatial",
}


def readPluginIds() -> dict[str, list[str]]:
    """
    Reads cached plugin ids along with categories from file and returns as a
    dict with plugin name as keys and list of strings as values. Order of values
    is ID, VST3 category, AAX category.
    """
    if not os.path.exists(ID_FILE):
        return {}
    pluginIds = {}
    with open(ID_FILE, "r", encoding="utf-8") as f:
        lines = f.readlines()
        for line in lines:
            kv = line.replace("\n", "").split(":")
            if len(kv) < 2:
                continue
            pluginIds[kv[0]] = kv[1:]
    return pluginIds


def addNewPluginId(plugin: str, cmakeOut: str, category: str = "") -> bool:
    """
    Adds a new plugin ID along with AAX and VST3 categories to plugin ID file.

    Args:
        plugin (str): Name of plugin.
        cmakeOut (str): Stdout from Cmake configure command. Used to deduce plugin ID.
        category (str): Category to add to record in ID file in AAX format.

    Returns:
        bool: True on success.
    """
    match = re.search("-- Generated new plugin id: ([^ ]*)\n", cmakeOut)
    if not match:
        print(f"{RED}Failed to get new plugin ID from cmake output.{BLACK}")
        return False
    newPluginId = match.group(1)
    if not newPluginId:
        return False
    if not _writePluginId(plugin, newPluginId, category):
        return False
    return True


def _writePluginId(plugin: str, newPluginId: str, category: str) -> bool:
    os.makedirs(ARTIFACTS_DIR, exist_ok=True)
    with open(ID_FILE, "a", encoding="utf-8") as f:
        st = f"{plugin}:{newPluginId}"
        if category:
            st += f":{CATEGORY_MAP[category]}:{category}"
        f.write(f"{st}\n")
    return True


def _overwriteIdFile(pluginIds: dict[str, list[str]]) -> bool:
    os.remove(ID_FILE)
    for name, info in pluginIds.items():
        if not _writePluginId(
            name, info[ID], info[AAX_CAT] if len(info) > 2 else ""
        ):
            return False
    return True


def updatePluginId(plugin: str, category: str) -> bool:
    pluginIds = readPluginIds()
    if not pluginIds or plugin not in pluginIds:
        return False
    aax_cat = category.strip()
    vst3_cat = CATEGORY_MAP[aax_cat]
    if len(pluginIds[plugin]) < 2:
        pluginIds[plugin] += [aax_cat, vst3_cat]
    else:
        pluginIds[plugin][AAX_CAT] = aax_cat
        pluginIds[plugin][VST3_CAT] = vst3_cat
    if not _overwriteIdFile(pluginIds):
        return False
    return True


def updatePluginHeader(plugins: list[str]) -> bool:
    tmp = """
#pragma once

/**
 * @file Plugins.h
 * @author Niels Thøgersen (niels.thoegersen@gmail.com)
 * @brief Autogenerated header containing all plugins.
 *
 * @copyright Copyright (c) 2026
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * You are free to download, build and use this code for commercial
 * purposes. Just don't resell it or a build of it, modified or otherwise.
 */

#ifdef NTFX_PLUGIN_FILE
  #include NTFX_PLUGIN_FILE
#endif
"""
    if not os.path.exists(PLUGIN_H_FILE):
        with open(PLUGIN_H_FILE, "w", encoding="utf-8") as f:
            f.write(tmp)
    with open(PLUGIN_H_FILE, "r", encoding="utf-8") as f:
        ls = f.readlines()
    ps = []
    for l in ls:
        if not l.startswith("#include") and ".h" in l:
            continue
        p = l.replace("#include \"plugins/", "").replace(".h\"", "").strip()
        if p not in ps:
            ps += [p]
    print(ps)
    print("")
    with open(PLUGIN_H_FILE, "a", encoding="utf-8") as f:
        for plugin in plugins:
            if plugin not in ps:
                f.write(f"#include \"plugins/{plugin}.h\"\n")
    return True


def configure(
    plugin: str,
    pluginIds: dict[str, list[str]],
    category: str = "",
    version: str = "",
    company: str = "",
    debug: bool = False,
) -> bool:
    """
    Configures Cmake for build

    Args:
        plugin (str): Name of plugin to build.
        pluginIds (dict[str, list[str]]): Information about plugins. See 'readPluginIds' for more.
        category (str): AAX format category for plugin. Overrides categories in 'pluginIds' if set.

    Returns:
        bool: True on success.
    """
    buildType = "Release"
    if debug:
        buildType = "Debug"
    if os.path.exists("build/CMakeCache.txt"):
        os.remove("build/CMakeCache.txt")
    args = [
        "cmake",
        "-B",
        BUILD_DIR,
        "-S",
        JUCE_WRAPPER_DIR,
        f"-DNTFX_PLUGIN={plugin}",
        f"-DCMAKE_BUILD_TYPE={buildType}",
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE",
    ]
    if sys.platform == "win32":
        args += ["-A", "x64"]
    if sys.platform == "darwin":
        args += ["-G Ninja"]
        args += ["CMAKE_C_COMPILER:FILEPATH=/usr/bin/clang"]
        args += ["CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++"]
    if version:
        args += [f"-DNTFX_VERSION={version}"]
    if category:
        args += [f"-DNTFX_AAX_CATEGORY={category}"]
        args += [f"-DNTFX_VST3_CATEGORY={CATEGORY_MAP[category]}"]
    if company:
        args += [f"-DNTFX_COMPANY={company}"]
    if plugin in pluginIds:
        info = pluginIds[plugin]
        args += [f"-DNTFX_ID={info[ID].strip()}"]
        print(
            f"{BLUE}Reusing existing plugin id for {plugin}: "
            f"{info[ID].strip()}.{BLACK}"
        )
        if not category and len(info) > 1:
            args += [f"-DNTFX_VST3_CATEGORY={info[VST3_CAT].strip()}"]
            print(
                f"{BLUE}Reusing VST3 category: {info[VST3_CAT].strip()}.{BLACK}"
            )
        if not category and len(info) > 2:
            args += [f"-DNTFX_AAX_CATEGORY={info[AAX_CAT].strip()}"]
            print(
                f"{BLUE}Reusing AAX category: {info[AAX_CAT].strip()}.{BLACK}"
            )

    print(f"{BLUE}Running cmake for plugin '{plugin}'.{BLACK}")
    print(f"{" ".join(args)}")
    res = subprocess.run(
        args, check=False, capture_output=True, env=os.environ.copy()
    )
    cmakeOut = res.stdout.decode()
    print(cmakeOut)
    if res.returncode:
        print(f"{RED}Cmake config failed:{BLACK}\n {res.stderr.decode()}")
        return False
    if plugin not in pluginIds:
        if not addNewPluginId(plugin, cmakeOut, category):
            return False
    elif len(pluginIds[plugin]) < 2 or pluginIds[plugin][AAX_CAT] != category:
        if category:
            if not updatePluginId(plugin, category):
                return False
    return True


def build() -> bool:
    """
    Builds plugin.

    Returns:
        bool: True on success.
    """
    print(f"{BLUE}Building.{BLACK}")
    args = [
        "cmake",
        "--build",
        BUILD_DIR,
        f"-j{cpu_count()}",
        "--config",
        "Release",
    ]
    res = subprocess.run(args, check=False)
    if res.returncode:
        print(f"{RED}Build failed.{BLACK}")
        return False
    return True


def runCtest() -> bool:
    """
    Runs Ctest.

    Returns:
        bool: True on success.
    """
    args = ["ctest", "--test-dir", BUILD_DIR]
    res = subprocess.run(args, check=False)
    return not bool(res.returncode)


def runAuVal() -> bool:
    """
    Runs Apple's AU validation utility for all plugins made by the 'NTfx' vendor.

    Returns:
        bool: True on success.
    """
    try:
        res = subprocess.run(["auval", "-vt", "aufx", "NTfx"], check=False)
    except FileNotFoundError:
        print(f"{RED}Auval utility not found.{BLACK}")
        return False
    return not bool(res.returncode)


def _artefactExists(plugin: str, target: str) -> bool:
    if sys.platform != "darwin":
        return True
    if os.path.exists(
        f"{BUILD_DIR}/{plugin}_artefacts/Release/{target}/"
        f"{plugin}.{package.TARGET_EXT_MAP[target]}"
    ):
        return True
    return False


def storeArtifacts(plugin: str) -> bool:
    """
    Stores output from build to 'artifacts' folder. Sorts according to plugin
    type, that is 'AAX', 'VST3', 'AU' and 'Standalone'.

    Args:
        plugin (str): Name of plugin to find and store artifacts for.

    Returns:
        bool: True on success.
    """
    art = f"{BUILD_DIR}{os.sep}{plugin}_artefacts{os.sep}{"Release"}{os.sep}"
    if not os.path.exists(art):
        return False
    targets = []
    for e in os.scandir(art):
        if e.is_dir():
            targets += [e.path.replace(art, "")]
    for target in targets:
        outDir = f"{ARTIFACTS_DIR}{os.sep}{target}"
        os.makedirs(outDir, exist_ok=True)
        subprocess.run(
            ["xattr", "-r", "-d", "*", f"{outDir}{os.sep}{plugin}"],
            check=False,
        )
        shutil.copytree(f"{art}{target}", outDir, dirs_exist_ok=True)
        print(f"{GREEN}Storing target {target} for plugin {plugin}.{BLACK}")
        if sys.platform == "win32" and target == "VST3":
            print(
                f"{BLUE}Add '{os.path.abspath(outDir)}' to you host/DAW plugin "
                "path or copy content to your plugin folder in order to use "
                f"plugins.{BLACK}"
            )
    return True


def buildPlugins(
    plugins: list[str],
    doTest: bool,
    category: str,
    version: str,
    company: str,
):
    pluginIds = readPluginIds()
    updatePluginHeader(plugins)
    for plugin in plugins:
        if not configure(plugin, pluginIds, category, version, company):
            return False
        if not build():
            return False
        if doTest:
            if not runCtest():
                return False
        if not storeArtifacts(plugin):
            return False
    if doTest and sys.platform == "darwin":
        if not runAuVal():
            return False
    return True


def run(plugins: list[str], args: dict) -> bool:
    version = args["version"]
    secrets = package.loadSecrets()
    for secret in package.SECRETS:
        if secret in args and args[secret]:
            secrets[secret] = args[secret].replace("/n", "")
    if not secrets:
        print(f"{RED}Faild to get credentials.{BLACK}")
        return False
    if not version:
        version = package.findVersion(args, secrets)
    if not version:
        print(f"{RED}Version is not provided. Aborting.{BLACK}")
        return False
    secrets["version"] = version
    if not buildPlugins(
        plugins, args["test"], args["category"], version, args["company"]
    ):
        return False
    if args["package"]:
        if not package.main(args):
            return False
    if not package.storeSecrets(secrets):
        return False
    return True


def addCatArg(parser: argparse.ArgumentParser):
    parser.add_argument(
        "--category",
        "-c",
        type=str,
        default="",
        choices=CATEGORY_MAP.keys(),
        help="Set the category you wish the plugin to be shown under in the "
        "host plugin list. Setting is cached, so it's only needed once per "
        "plugin, and never when building all plugins.",
    )


def createParser():
    parser = argparse.ArgumentParser(description="Build plugins.")
    parser.add_argument(
        "plugins",
        nargs="*",
        type=str,
        help="Plugins to build, placed in 'plugins' dir. Defaults to 'all', "
        "which builds all plugins.",
        default=["all"],
    )
    parser.add_argument(
        "--test",
        "-t",
        action="store_true",
        help="Apply uint tests before and validation after build.",
    )
    addCatArg(parser)
    parser.add_argument(
        "--package",
        "-p",
        action="store_true",
        help="For MacOS, package plugins as an installer. Requires 'package' "
        "command to have been run with full credentials and at least once, "
        "which will cache the credentials.",
    )
    parser.add_argument(
        "--version",
        "-v",
        help="Version to be used for all plugins and installer. Cached and "
        "minor minor number auto-incremented if not given.",
    )
    parser.add_argument(
        "--company",
        help="Company/vendor of plugins.",
        default="NTfx",
    )
    return parser
