classdef ntTilt_01 < audioPlugin
  properties
    bypass = false;
    tilt_ui = 0;
  end
  properties (Access = private)
    fs = 44100;
    n_stages = 8;
    freqs = zeros(8);
    alpha = 0;
    gain_stage_lin = 1;
    tilt_lin = 0;
    st_xn1 = 0;
    st_yn1 = 0;
  end
  properties (Constant)
    PluginInterface = audioPluginInterface( ...
      audioPluginParameter('tilt_ui', ...
      'DisplayName', 'Tilt', ...
      'Mapping', {'lin', -12, 12}, ...
      'Label', 'dB', ...
      'Style', 'rotary', ...
      'Layout', [2, 1]), ...
      audioPluginParameter('bypass', ...
      'Mapping', {'enum', 'In', 'Out'}, ...
      'Style', 'vtoggle', ...
      'Layout', [4, 1], ...
      'DisplayName', 'Master Bypass'), ...
      audioPluginGridLayout( ...
      'RowHeight', [30, 150, 15, 100, 15], ...
      'ColumnWidth', [100], ...
      'RowSpacing', 30), ...
      'PluginName', 'ntTilt_01', ...
      'VendorName', 'NT', ...
      'VendorVersion', '0.1.0', ...
      'InputChannels', 2, ...
      'OutputChannels', 2, ...
      'BackgroundImage', 'logo.png' ...
    );
  end
  methods
    function y = process(p, x)
      x(~isfinite(x)) = 0;
      if p.bypass
        y = x;
      else
        y = process_tilt(p, x);
      end
    end

    function update(p)
      p.freqs = logspace(log10(20), log10(20e3), p.n_stages + 1);
      p.freqs = p.freqs(2:end);
      z = 2 .* pi .* p.freqs ./ p.fs;
      p.alpha = z ./ (z + 1);

      p.tilt_lin = 10 .^ (p.tilt_ui / 20);
      g_shelf_db = -2 .* p.tilt_ui ./ p.n_stages;
      p.gain_stage_lin = 10 .^ (g_shelf_db ./ 20) - 1;
      p.st_xn1 = zeros(p.n_stages, 2);
      p.st_yn1 = zeros(p.n_stages, 2);
    end
    function reset(p)
      p.fs = getSampleRate(p);
      update(p);
    end
    function set.tilt_ui(p, val)
      p.tilt_ui = val;
      update(p);
    end
  end
end
