classdef bigger < audioPlugin
   properties
      fs = 0;
      gain = 4;
      freq = 200;
      bypass = false;

      A = 1;
      alpha = 0;
      st = 0;
   end
   properties (Constant)
      PluginInterface = audioPluginInterface(...
         audioPluginParameter('gain', ...
         'DisplayName', 'Gain', ...
         'Mapping', {'lin', 0, 12}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [2, 1]), ...
         audioPluginParameter('freq', ...
         'DisplayName', 'Frequency', ...
         'Mapping', {'log', 50, 1000}, ...
         'Label', 'Hz', ...
         'Style', 'rotary', ...
         'Layout', [2, 2]), ...
         audioPluginParameter('bypass', ...
         'Mapping', {'enum', 'In', 'Out'}, ...
         'Style', 'vtoggle', ...
         'Layout', [4, 2], ...
         'DisplayName', 'Master Bypass'), ...
         audioPluginGridLayout(...
         'RowHeight', [30, 150, 15, 100, 15], ...
         'ColumnWidth', [100, 100], ...
         'RowSpacing', 30), ...
         'PluginName', 'Bigger', ...
         'VendorName', 'NT', ...
         'InputChannels', 2, ...
         'OutputChannels', 2, ...
         'BackgroundImage', 'logo.png' ...
         );
   end
   methods
      function y = process(p, x)
         n = length(x);
         y = zeros(n, 2);
         if p.bypass == true
            y = x;
         else
            state = p.st;
            for i = 1:n
               xMid = x(i, 1) + x(i, 2);
               xSide = x(i, 1) - x(i, 2);

               yLpf = p.alpha * xSide + (1 - p.alpha) * state;
               state = yLpf;
               ySide = yLpf * (1 - p.A) + xSide;

               yMid = xMid;
               y(i, 1) = 0.5 * (yMid + ySide);
               y(i, 2) = 0.5 * (yMid - ySide);
            end
            p.st = state;
         end
      end
      function set.freq(p, val)
         p.freq = val;
         update(p);
      end
      function set.gain(p, val)
         p.gain = val;
         update(p);
      end
      function update(p)
         p.alpha = 1 - exp(-2 * pi * p.freq / p.fs);
         p.A = 10^(p.gain / 20);
      end
      function reset(p)
         p.fs = getSampleRate(p);
         update(p);
      end
   end
end
