classdef ntChorus < audioPlugin
  properties
    fs = 48000;
    bypass = false;
    trigged = true;
    triple = false;
    modFreq = 0.2;
    modDepth = 0.50;
    modPhase = 90;
    mix = 0;
    mix_gui = 50;
    len_delayLine = 48000;
    dLine = zeros(48001, 2);
    store_loc = 1;
    t_delay = 0.02;
    n_delay = 0;
    tCount = 1;
    % state = zeros(9, 1);
    a_rect = 0;
    t_peak = 0.5;
    f_diff = 0;
    sens = 0.5;
    f_lpf1 = 6000;
    st_lpf1 = zeros(1, 2);
    a_lpf1 = 0;
    samplesSinceTrig = 0;
    t_reTrig = 1/64;
    n_reTrig = 500;
    a_avg = 0;
    t_avg = 2;
    a_diff_smooth = 0;
    t_diff_smooth = 0.002;
    rnd = rand(1024, 1);

    % Calculates adaptive FIR filter
    % w = resulting coefficients, size m+1 x n
    % e = error vector
    % x = input signal
    % y = output of filter to be modelled
    % w_init = initial coefficients
    % mu = step size
    % states
    m = 6;
    mu_0 = 0.99;
    w = zeros(6 + 1, 1024);
  end
  properties (Constant)
    % PluginInterface = audioPluginInterface( ...
    %    audioPluginParameter('sens', ...
    %    'DisplayName', 'Sens', ...
    %    'Mapping', {'lin', 0, 1}, ...
    %    'Label', '', ...
    %    'Style', 'rotary', ...
    %    'Layout', [2, 1]), ...
    %    audioPluginParameter('t_delay', ...
    %    'DisplayName', 'Delay', ...
    %    'Mapping', {'lin', 0, 0.1}, ...
    %    'Label', 's', ...
    %    'Style', 'rotary', ...
    %    'Layout', [2, 2]), ...
    %    audioPluginParameter('modDepth', ...
    %    'DisplayName', 'Depth', ...
    %    'Mapping', {'lin', 0, 1}, ...
    %    'Label', '', ...
    %    'Style', 'rotary', ...
    %    'Layout', [2, 3]), ...
    %    audioPluginParameter('mix_gui', ...
    %    'DisplayName', 'Mix', ...
    %    'Mapping', {'lin', 0, 100}, ...
    %    'Label', '%', ...
    %    'Style', 'rotary', ...
    %    'Layout', [2, 4]), ...
    %    audioPluginParameter('t_reTrig', ...
    %    'DisplayName', 'Retrig', ...
    %    'Mapping', {'lin', 0, 0.125}, ...
    %    'Label', '', ...
    %    'Style', 'rotary', ...
    %    'Layout', [4, 1]), ...
    %    audioPluginParameter('trigged', ...
    %    'Mapping', {'enum', 'Sine', 'Trigged'}, ...
    %    'Style', 'vtoggle', ...
    %    'Layout', [4, 2], ...
    %    'DisplayName', 'LFO'), ...
    %    audioPluginParameter('triple', ...
    %    'Mapping', {'enum', '2', '3'}, ...
    %    'Style', 'vtoggle', ...
    %    'Layout', [4, 3], ...
    %    'DisplayName', 'Voices'), ...
    %    audioPluginParameter('bypass', ...
    %    'Mapping', {'enum', 'In', 'Out'}, ...
    %    'Style', 'vtoggle', ...
    %    'Layout', [4, 4], ...
    %    'DisplayName', 'Master Bypass'), ...
    %    audioPluginGridLayout( ...
    %    'RowHeight', [30, 150, 15, 100, 15], ...
    %    'ColumnWidth', [100, 100, 100, 100], ...
    %    'RowSpacing', 30), ...
    %    'PluginName', 'ntChorus', ...
    %    'VendorName', 'NT', ...
    %    'InputChannels', 2, ...
    %    'OutputChannels', 2, ...
    %    'BackgroundImage', 'logo.png' ...
    % );
    PluginInterface = audioPluginInterface( ...
      audioPluginParameter('t_delay', ...
      'DisplayName', 'Delay', ...
      'Mapping', {'lin', 0, 0.1}, ...
      'Label', 's', ...
      'Style', 'rotary', ...
      'Layout', [2, 1]), ...
      audioPluginParameter('modFreq', ...
      'DisplayName', 'Freq', ...
      'Mapping', {'log', 0.1, 10}, ...
      'Label', '', ...
      'Style', 'rotary', ...
      'Layout', [2, 2]), ...
      audioPluginParameter('modDepth', ...
      'DisplayName', 'Depth', ...
      'Mapping', {'lin', 0, 1}, ...
      'Label', '', ...
      'Style', 'rotary', ...
      'Layout', [2, 3]), ...
      audioPluginParameter('mix_gui', ...
      'DisplayName', 'Mix', ...
      'Mapping', {'lin', 0, 100}, ...
      'Label', '%', ...
      'Style', 'rotary', ...
      'Layout', [2, 4]), ...
      audioPluginParameter('sens', ...
      'DisplayName', 'Sens', ...
      'Mapping', {'lin', 0, 1}, ...
      'Label', '', ...
      'Style', 'rotary', ...
      'Layout', [4, 1]), ...
      audioPluginParameter('trigged', ...
      'Mapping', {'enum', 'Sine', 'Trigged'}, ...
      'Style', 'vtoggle', ...
      'Layout', [4, 2], ...
      'DisplayName', 'LFO'), ...
      audioPluginParameter('triple', ...
      'Mapping', {'enum', '2', '3'}, ...
      'Style', 'vtoggle', ...
      'Layout', [4, 3], ...
      'DisplayName', 'Voices'), ...
      audioPluginParameter('bypass', ...
      'Mapping', {'enum', 'In', 'Out'}, ...
      'Style', 'vtoggle', ...
      'Layout', [4, 4], ...
      'DisplayName', 'Master Bypass'), ...
      audioPluginGridLayout( ...
      'RowHeight', [30, 150, 15, 100, 15], ...
      'ColumnWidth', [100, 100, 100, 100], ...
      'RowSpacing', 30), ...
      'PluginName', 'ntChorusLite', ...
      'VendorName', 'NT', ...
      'InputChannels', 2, ...
      'OutputChannels', 2, ...
      'BackgroundImage', 'logo.png' ...
    );
  end
  methods
    function y = process(p, x)
      n = length(x);
      y = zeros(n, 2);
      lLoc = [0 0];
      y_est = 0;
      x_m = zeros(p.m + 1, 1);
      n_mod = [0, 0];

      % n_mod = [p.state(5), p.state(6)];
      % y_rect_1 = p.state(1);
      % y_rect_2 = p.state(2);
      % y_diff_1 = p.state(3);
      % y_diff_2 = p.state(4);
      % y_avg_1 = p.state(7);
      % y_diff_smooth_1 = p.state(8);
      % sum_diff = p.state(9);

      x(~isreal(x)) = 0;

      if (p.bypass == true)
        y = x;
      else
        for i = 1:n
          p.dLine(p.store_loc, :) = x(i, :);

          if (p.trigged == true)
            % % LPF
            % y_lpf = p.a_lpf1 * x(i, :) + (1 - p.a_lpf1) * p.st_lpf1;
            % p.st_lpf1 = y_lpf;

            % % rectify and smooth
            % y_rect = max(max(abs(y_lpf)), p.a_rect * y_rect_1 + ...
            %    (1 - p.a_rect) * max(abs(y_lpf)));

            % % Take average
            % y_avg = p.a_avg * y_rect + (1 - p.a_avg) * y_avg_1;
            % y_avg_1 = y_avg;

            % % differentiate
            % y_diff = y_rect - y_rect_2;

            % % store state
            % y_rect_2 = y_rect_1;
            % y_rect_1 = y_rect;

            % % compare
            % if (y_diff > y_diff_1) && (y_diff > 0)
            %    sum_diff = sum_diff + y_diff;
            % else
            %    sum_diff = 0;
            % end
            % y_norm = sum_diff; % / y_avg;

            % trig = false;
            % if y_norm > p.sens
            %    if p.samplesSinceTrig > p.n_reTrig
            %       trig = true;
            %       p.samplesSinceTrig = 0;
            %    end
            % end
            % p.samplesSinceTrig = p.samplesSinceTrig + 1;

            % % store state
            % y_diff_2 = y_diff_1;
            % y_diff_1 = y_diff;

            if i > p.m
              % make new x_m-vector
              x_m = flip(p.rnd((i - p.m):i));

              % filter input with adaptive filter
              y_est = p.w(:, i)' * x_m;
            end

            % calculate error
            e = x(i) - y_est;

            % calculate coefficients for the next iteration
            if i ~= n
              p.w(:, (i + 1)) = p.w(:, i) + p.mu_0 / (x_m' * x_m) * x_m;
              if isnan(p.w(:, (i + 1))) == true
                p.w(:, (i + 1)) = 0;
              end
            end

            trig = false;
            if e > p.sens
              if p.samplesSinceTrig > p.n_reTrig
                trig = true;
                p.samplesSinceTrig = 0;
              end
            end
            p.samplesSinceTrig = p.samplesSinceTrig + 1;

            % calculate delay
            if trig == true
              if p.triple == false
                n_mod(1) = 0;
              else
                n_mod(1) = round((p.rnd(n - i) * 2 - 1) * p.n_delay * p.modDepth) + p.n_delay;
              end
              n_mod(2) = round((p.rnd(i) * 2 - 1) * p.n_delay * p.modDepth) + p.n_delay;
              % disp("trigged") %, diff = " + num2str(y_norm) + ", t_mod = " + num2str(n_mod ./ p.fs));
            end

          else % Trigged
            % calculate modulated delay time
            n_mod(1) = round(saw(2 .* pi .* p.modFreq ./ p.fs .* p.tCount) .* ...
              p.n_delay .* p.modDepth) + p.n_delay;
            n_mod(2) = round(saw(2 .* pi .* p.modFreq ./ p.fs .* p.tCount + ...
              p.modPhase * pi / 180) .* p.n_delay .* p.modDepth) + p.n_delay;
            p.tCount = p.tCount + 1;
          end

          lLoc(1) = p.store_loc - n_mod(1);
          if (lLoc(1) < 1)
            lLoc(1) = lLoc(1) + p.len_delayLine;
          end
          lLoc(2) = p.store_loc - n_mod(2);
          if (lLoc(2) < 1)
            lLoc(2) = lLoc(2) + p.len_delayLine;
          end

          if p.triple == true
            y(i, 1) = p.mix .* p.dLine(lLoc(1), 1) + (1 - p.mix) .* x(i, 1);
            y(i, 2) = p.mix .* p.dLine(lLoc(2), 2) + (1 - p.mix) .* x(i, 2);
          else
            y(i, 1) = x(i, 1);
            y(i, 2) = p.dLine(lLoc(2), 2);
          end
          p.store_loc = p.store_loc + 1;
          p.store_loc(p.store_loc > p.len_delayLine) = 1;
        end
      end
      % p.state = [y_rect_1; y_rect_2; y_diff_1; y_diff_2; ...
      % n_mod(1); n_mod(2); y_avg_1; y_diff_smooth_1; sum_diff];
      % p.state = [0; 0; 0; 0; ...
      % n_mod(1); n_mod(2); 0; 0; 0];

    end
    function y = saw(x)
      % x   y
      % 0 ~ 0
      % pi/2 ~ 1
      % pi ~ 0
      % 3pi/2 ~ -1

      n = length(x);
      y = zeros(n, 1);
      for i = 1:n
        x_ = mod(x(i), 2 * pi);
        if x_ < 0
          x_ = x_ + 2 * pi;
        end

        alpha = 2 / pi;

        if x_ < pi / 2
          y_ = x_ * alpha;
        elseif x_ < 3 * pi / 2
          y_ = -x_ * alpha + 2;
        else
          y_ = x_ * alpha - 4;
        end
        y(i) = y_;
      end
    end
    function reset(p)
      p.fs = getSampleRate(p);
      update(p)
    end
    function update(p)
      p.mix = p.mix_gui / 100;
      p.n_delay = round(p.t_delay * p.fs);
      %p.state(6) = p.n_delay;
      % p.a_rect = exp(-2200 / (p.t_peak * p.fs));
      % p.a_lpf1 = 1 - exp(-2 .* pi .* p.f_lpf1 ./ p.fs);
      % p.a_avg = 1 - exp(-1 / (p.t_avg * p.fs));
      % p.a_diff_smooth = 1 - exp(-1 / (p.t_diff_smooth * p.fs));
      p.n_reTrig = p.t_reTrig * p.fs;
    end
    function set.sens(p, val)
      p.sens = val;
      update(p);
    end
    function set.t_delay(p, val)
      p.t_delay = val;
      update(p);
    end
    function set.modDepth(p, val)
      p.modDepth = val;
      update(p);
    end
    function set.mix_gui(p, val)
      p.mix_gui = val;
      update(p);
    end
    function set.t_reTrig(p, val)
      p.t_reTrig = val;
      update(p);
    end
  end
end

%%%%%%%%%%%%%% %%%%%% %%%%%%
% audioPluginParameter('t_avg', ...
% 'DisplayName', 'Avg', ...
% 'Mapping', {'lin', 0, 10}, ...
% 'Label', 's', ...
% 'Style', 'rotary', ...
% 'Layout', [6, 1]), ...
% audioPluginParameter('t_diff_smooth', ...
% 'DisplayName', 'Diff Smooth', ...
% 'Mapping', {'lin', 0, 0.1}, ...
% 'Label', 's', ...
% 'Style', 'rotary', ...
% 'Layout', [6, 2]), ...
