classdef ntPassive_02 < audioPlugin
   properties
      bypass = false;
      zero_at_nyquist = false;
      clip_bypass = false;
      f_lf = 100;
      g_lf_db = 0;
      f_hf = 2000;
      g_hf_db = 0;
      f_mf = 1000;
      g_mf_db = 0;
      g_db = 0;
      g_clip_db = 0;
      g_clip_lf_db = 0;
      g_clip_mf_db = 0;
      g_clip_hf_db = 0;
   end
   properties (Access = private)
      g_lf = 0;
      g_hf = 0;
      g_bp = 0;
      g = 0;
      alpha_bp_lpf = 0;
      alpha_bp_hpf = 0;
      alpha_lpf = 0;
      alpha_hpf = 0;
      fs = 44100;
      state = zeros(8, 2);
      g_clip = 1;
      g_clip_recipr = 1;
      g_clip_lf = 1;
      g_clip_lf_recipr = 1;
      g_clip_mf = 1;
      g_clip_mf_recipr = 1;
      g_clip_hf = 1;
      g_clip_hf_recipr = 1;
   end
   properties (Constant)
      PluginInterface = audioPluginInterface( ...
         audioPluginParameter('f_lf', ...
         'DisplayName', 'Low Freq', ...
         'Mapping', {'log', 10, 1e3}, ...
         'Label', 'Hz', ...
         'Style', 'rotary', ...
         'Layout', [2, 1]), ...
         audioPluginParameter('f_mf', ...
         'DisplayName', 'Mid Freq', ...
         'Mapping', {'log', 20, 20e3}, ...
         'Label', 'Hz', ...
         'Style', 'rotary', ...
         'Layout', [2, 2]), ...
         audioPluginParameter('f_hf', ...
         'DisplayName', 'High Freq', ...
         'Mapping', {'log', 1e3, 100e3}, ...
         'Label', 'Hz', ...
         'Style', 'rotary', ...
         'Layout', [2, 3]), ...
         audioPluginParameter('g_lf_db', ...
         'DisplayName', 'Lo Gain', ...
         'Mapping', {'lin', 0, 24}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [4, 1]), ...
         audioPluginParameter('g_mf_db', ...
         'DisplayName', 'Mid Gain', ...
         'Mapping', {'lin', 0, 24}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [4, 2]), ...
         audioPluginParameter('g_hf_db', ...
         'DisplayName', 'High Gain', ...
         'Mapping', {'lin', 0, 24}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [4, 3]), ...
         audioPluginParameter('g_clip_db', ...
         'DisplayName', 'Wide band drive', ...
         'Mapping', {'lin', -40, 40}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [4, 5]), ...
         audioPluginParameter('g_db', ...
         'DisplayName', 'Trim', ...
         'Mapping', {'lin', -24, 0}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [4, 6]), ...
         audioPluginParameter('g_clip_lf_db', ...
         'DisplayName', 'Low drive', ...
         'Mapping', {'lin', -40, 40}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [6, 1]), ...
         audioPluginParameter('g_clip_mf_db', ...
         'DisplayName', 'Mid drive', ...
         'Mapping', {'lin', -40, 40}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [6, 2]), ...
         audioPluginParameter('g_clip_hf_db', ...
         'DisplayName', 'High drive', ...
         'Mapping', {'lin', -40, 40}, ...
         'Label', 'dB', ...
         'Style', 'rotary', ...
         'Layout', [6, 3]), ...
         audioPluginParameter('clip_bypass', ...
         'DisplayName', 'All saturation', ...
         'Mapping', {'enum', 'In', 'Out'}, ...
         'Style', 'vtoggle', ...
         'Layout', [6, 4]), ...
         audioPluginParameter('zero_at_nyquist', ...
         'DisplayName', 'Zero at Nyquist', ...
         'Mapping', {'enum', 'In', 'Out'}, ...
         'Style', 'vtoggle', ...
         'Layout', [6, 5]), ...
         audioPluginParameter('bypass', ...
         'DisplayName', 'Master Bypass', ...
         'Mapping', {'enum', 'In', 'Out'}, ...
         'Style', 'vtoggle', ...
         'Layout', [6, 6]), ...
         audioPluginGridLayout( ...
         'RowHeight', [30, 150, 15, 150, 15 100, 15], ...
         'ColumnWidth', [100, 100, 100, 100, 100, 100], ...
         'RowSpacing', 30), ...
         'PluginName', 'ntPassive_01', ...
         'VendorName', 'NT', ...
         'VendorVersion', '0.2.0', ...
         'InputChannels', 2, ...
         'OutputChannels', 2, ...
         'BackgroundImage', 'logo.png' ...
      );
   end
   methods
      function y = softClip(p, x, g, g_recipr)
         y = x;
         if ~p.clip_bypass
            x = x .* g;
            if x(1) > 1
               y(1) = 1;
            elseif x(1) < -1
               y(1) = -1;
            else
               y(1) = 1.5 .* x(1) - 0.5 .* x(1) .^ 3;
            end

            if x(2) > 1
               y(2) = 1;
            elseif x(2) < -1
               y(2) = -1;
            else
               y(2) = 1.5 .* x(2) - 0.5 .* x(2) .^ 3;
            end
            y = y .* g_recipr .* 0.6667;
         end
      end
      function y = process(p, x)
         x(~isfinite(x)) = 0;
         n = length(x);
         y = zeros(n, 2);
         if p.bypass
            y = x;
         else
            xn1_bp_lpf = p.state(1, :);
            yn1_bp_lpf = p.state(2, :);
            xn1_bp_hpf = p.state(3, :);
            yn1_bp_hpf = p.state(4, :);
            xn1_lpf = p.state(5, :);
            yn1_lpf = p.state(6, :);
            xn1_hpf = p.state(7, :);
            yn1_hpf = p.state(8, :);
            for i = 1:n
               % LPF
               if ~p.zero_at_nyquist
                  y_lpf = 0.5 .* p.alpha_lpf .* (x(i, :) + xn1_lpf) + (1 - p.alpha_lpf) .* yn1_lpf;
               else
                  y_lpf = p.alpha_lpf .* x(i, :) + (1 - p.alpha_lpf) .* yn1_lpf;
               end
               xn1_lpf = x(i, :);
               yn1_lpf = y_lpf;

               y_lpf_cl = softClip(p, y_lpf, p.g_clip_lf, p.g_clip_lf_recipr);

               % HPF
               y_hpf = p.alpha_hpf .* (yn1_hpf + x(i, :) - xn1_hpf);
               xn1_hpf = x(i, :);
               yn1_hpf = y_hpf;

               y_hpf_cl = softClip(p, y_hpf, p.g_clip_hf, p.g_clip_hf_recipr);

               % Band pass
               % Band Pass LPF
               if ~p.zero_at_nyquist
                  y_bp_lpf = 0.5 .* p.alpha_bp_lpf .* (x(i, :) + xn1_bp_lpf) + (1 - p.alpha_bp_lpf) .* yn1_bp_lpf;
               else
                  y_bp_lpf = p.alpha_bp_lpf .* x(i, :) + (1 - p.alpha_bp_lpf) .* yn1_bp_lpf;
               end
               xn1_bp_lpf = x(i, :);
               yn1_bp_lpf = y_bp_lpf;

               % Band Pass HPF
               yn0_bp_hpf = p.alpha_bp_hpf .* (yn1_bp_hpf + y_bp_lpf - xn1_bp_hpf);
               xn1_bp_hpf = y_bp_lpf;
               yn1_bp_hpf = yn0_bp_hpf;
               y_bp = yn0_bp_hpf .* 2;

               y_bp_cl = softClip(p, y_bp, p.g_clip_mf, p.g_clip_mf_recipr);

               y_sum = p.g .* (x(i, :) + ...
                  y_bp_cl * p.g_bp + ...
                  y_lpf_cl * p.g_lf + ...
                  y_hpf_cl * p.g_hf);

               y(i, :) = softClip(p, y_sum, p.g_clip, p.g_clip_recipr);
            end
            p.state(1, :) = xn1_bp_lpf;
            p.state(2, :) = yn1_bp_lpf;
            p.state(3, :) = xn1_bp_hpf;
            p.state(4, :) = yn1_bp_hpf;
            p.state(5, :) = xn1_lpf;
            p.state(6, :) = yn1_lpf;
            p.state(7, :) = xn1_hpf;
            p.state(8, :) = yn1_hpf;
         end
      end
      function update(p)
         p.g_lf = 10 ^ (p.g_lf_db / 20) - 1;
         z = 2 .* pi .* p.f_lf ./ p.fs;
         p.alpha_lpf = z ./ (z + 1);
         p.g_clip_lf = 10 ^ (p.g_clip_lf_db / 20);
         p.g_clip_lf_recipr = 1 / p.g_clip_lf;

         p.g_bp = 10 ^ (p.g_mf_db / 20) - 1;
         z = 2 .* pi .* p.f_mf ./ p.fs;
         p.alpha_bp_hpf = 1 ./ (z + 1);
         p.alpha_bp_lpf = z ./ (z + 1);
         p.g_clip_mf = 10 ^ (p.g_clip_mf_db / 20);
         p.g_clip_mf_recipr = 1 / p.g_clip_mf;

         p.g_hf = 10 ^ (p.g_hf_db / 20) - 1;
         z = 2 .* pi .* p.f_hf ./ p.fs;
         p.alpha_hpf = 1 ./ (z + 1);
         p.g_clip_hf = 10 ^ (p.g_clip_hf_db / 20);
         p.g_clip_hf_recipr = 1 / p.g_clip_hf;

         p.g = 10 ^ (p.g_db / 20);
         p.g_clip = 10 ^ (p.g_clip_db / 20);
         p.g_clip_recipr = 1 / p.g_clip;
      end
      function reset(p)
         p.fs = getSampleRate(p);
         update(p);
      end
      function set.g_lf_db(p, val)
         p.g_lf_db = val;
         update(p);
      end
      function set.g_mf_db(p, val)
         p.g_mf_db = val;
         update(p);
      end
      function set.g_hf_db(p, val)
         p.g_hf_db = val;
         update(p);
      end
      function set.f_lf(p, val)
         p.f_lf = val;
         update(p);
      end
      function set.f_mf(p, val)
         p.f_mf = val;
         update(p);
      end
      function set.f_hf(p, val)
         p.f_hf = val;
         update(p);
      end
      function set.g_db(p, val)
         p.g_db = val;
         update(p);
      end
      function set.g_clip_db(p, val)
         p.g_clip_db = val;
         update(p);
      end
      function set.g_clip_lf_db(p, val)
         p.g_clip_lf_db = val;
         update(p);
      end
      function set.g_clip_mf_db(p, val)
         p.g_clip_mf_db = val;
         update(p);
      end
      function set.g_clip_hf_db(p, val)
         p.g_clip_hf_db = val;
         update(p);
      end
   end
end
